apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

components:
  - ./components/secret

helmCharts:
  - repo: https://charts.bitnami.com/bitnami
    name: redis
    releaseName: shopping-cart
    namespace: redis
    valuesInline:
      sentinel:
        enabled: true
        masterSet: shopping-cart
        persistence:
          enabled: true
      auth:
        existingSecret: shopping-cart-redis
        existingSecretPasswordKey: db-password
